version: '3'
services:
  db:
    image: ulife-share-db
    container_name: ulife-share-db
    build:
      context: .
      dockerfile: ./build/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: todo-password
      TZ: "UTC"
    ports:
      - 3306:3306
  api:
    image: ulife-share-server
    container_name: ulife-share-server
    build:
      context: .
      dockerfile: ./build/api/dev/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/myapp
    depends_on:
      - db
