version: '3'
services:
  db:
    image: mysql:8.0
    container_name: ulife-share-db
    environment:
      MYSQL_DATABASE: ulifeshare
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: "UTC"
    volumes:
      - db_data:/var/lib/mysql
      - ./build/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
  api:
    image: ulife-share-server
    container_name: ulife-share-server
    build:
      context: .
      dockerfile: ./build/api/dev/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/myapp
    depends_on:
      - db
volumes:
  db_data:
